"""
Upstox WebSocket client (v9.2 scaffold)
TODO: OAuth auth, subscribe, reconnect.
"""
class UpstoxWebSocketClient:
    def connect(self): ...
    def subscribe(self,instruments): ...
    def disconnect(self): ...
